config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :users do
    resources :addresses
    resources :posts
  end
  root 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # when single resource then we don't have index as we have single resource we dont want to list it
  # and id is also not there as it is single entity
end

app/models/address.rb
# == Schema Information
#
# Table name: addresses
#
#  id         :integer          not null, primary key
#  house_no   :string
#  street     :string
#  city       :string
#  state      :string
#  country    :string
#  pincode    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Address < ApplicationRecord
  validates :house_no,
    presence: true,
    format: {
      with: /\A[A-Z]?\d+\z/
    }
    validates :street, presence: true
    validates :city, presence: true
    validates :state, presence: true
    validates :pincode,
      presence: true,
      format: {
        with: /\A\d{6}\z/
      }
    belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Post < ApplicationRecord
  validates :title,
    presence: true,
    length: {maximum: 20}
  validates :content,
    presence: true,
    length: {maximum: 800}
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  name          :string
#  gender        :string
#  dob           :date
#  mobile_number :string
#  email         :string
#  password      :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  last_name     :string
#

class User < ApplicationRecord
  validates :name,
    presence: true,
    format: {
      with: /\A[a-zA-Z]\w*\z/
    }

  validates :email,
    presence: true,
    format: {
      with: /\A[a-zA-Z]\w*@\w*[.]com\z/
    }

  validates :mobile_number,
    presence: true,
    format: {
      with: /\A\d{10}\z/
    }

  validates :password,
    confirmation: true,
    presence: true,
    length: {
      minimum: 8
    }
  validates :gender,
    presence: true,
    inclusion: {
      in: %w(M F O),
      message: "%{value} is not valid!"
    }
  
  validates :dob, presence: true
  has_one :address, dependent: :destroy
  has_many :posts
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def show
  	@user = User.find(params[:id])
    @address = Address.find_by(user_id: @user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @list = User.all
    respond_to do |format|
    	format.html
    	format.json { render :json => @list.to_json }
  	end
  end

  def new
    @user = User.new
  end

  def create
  	@user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path}
        format.json { render :json => User.last.to_json }
      else
        format.html { render 'new' }
        format.json { render :json => @user.errors.to_json }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      respond_to do |format|
        format.html
        format.json {render :json => @user.to_json}
      end
    end
  end

  def destroy
  	@user = User.find(params[:id])
    respond_to do |format|
      if @user.destroy
        format.html {redirect_to root_path}
        format.json {render :json => "Deleted successfully".to_json}
      end
    end
  	# redirect_to root_path if @user.destroy
  end

  def show
  	@user = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:name, :last_name, :mobile_number, :password_confirmation, :email, :dob, :password, :gender)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def format_time(time)
    time.strftime("%d-%m-%Y")
  end
end

app/views/addresses/show.html.haml
%center
  %h1 User Address
  %table{:cellpadding => "10"}
    %tr
      %th Name
      %th House no
      %th Street
      %th City
      %th State
      %th Pincode
      %tr
        %td= @user.name+" "+@user.last_name
        %td= @address.house_no
        %td= @address.street
        %td= @address.city
        %td= @address.state
        %td= @address.pincode
      %tr
        %td= link_to 'Back', users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Demo
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/edit.html.haml
- provide(tile: 'Update')
%center
  %h1 Update Form
  - if @user.errors.any?
    %h2
      Errors:
    %ul
    - @user.errors.full_messages.each do |msg|
      %li= msg
  = form_with model: @user, local: true, method: :put  do |form|
    %table
      %tr
        %td
          = form.label :name
        %td
          = form.text_field :name
      %tr
        %td
          = form.label :last_name
        %td
          = form.text_field :last_name
      %tr
        %td
          = form.label :email
        %td
          = form.text_field :email
      %tr
        %td
          = form.label :mobile_number
        %td
          = form.text_field :mobile_number
      %tr
        %td
          = form.label :gender
      %tr
        %td
          = form.label :male
        %td
          = form.radio_button 'gender', 'M'
      %tr
        %td
          = form.label :female
        %td
          = form.radio_button 'gender', 'F'
      %tr
        %td
          = form.label :other
        %td
          = form.radio_button 'gender', 'O'
      %tr
        %td
          = form.label :password
        %td
          = form.text_field :password
      %tr
        %td
          = form.label :password_confirmation  
        %td
          = form.text_field :password_confirmation
      %tr
        %td
          = form.label :dob
        %td
          = form.date_field 'dob'
      %tr
        %td
        %td
          = form.submit
  = link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing Users
%p The List of user:
%table{:cellpadding => "10"}
  %tr
    %th Name
    %th Gender
    %th EMail
    %th DOB
    %th Mobile Number
  - @list.each do |data|
    %tr
      %td= link_to data.name, user_path(data)
      %td= data.gender
      %td= data.email
      %td= data.dob
      %td= data.mobile_number
      //%td= link_to 'Delete', user_path(data), method: :delete, class: 'btn btn-primary'
      %td= button_to 'Delete', { action: 'destroy', id: data.id }, :class => 'btn btn-warning', method: :delete, data: { confirm: "Are you sure?" }
      //%td= link_to 'Edit', edit_user_path(data), method: :get
      %td= button_to 'Update', { action: 'edit', id: data.id }, :class => 'btn btn-danger', method: :get, data: { confirm: "Are you sure?" }
= link_to 'SignUP', 'users/new'

app/views/users/new.html.haml
- provide(tile: 'SignUP')
%center
  %h1 Signup form
  - if @user.errors.any?
    %h2
      Errors:
    %ul
    - @user.errors.full_messages.each do |msg|
      %li= msg
  = form_with model: @user, local: true do |form|
    %table
      %tr
        %td
          = form.label :name
        %td
          = form.text_field :name
      %tr
        %td
          = form.label :last_name
        %td
          = form.text_field :last_name
      %tr
        %td
          = form.label :email
        %td
          = form.text_field :email
      %tr
        %td
          = form.label :mobile_number
        %td
          = form.text_field :mobile_number
      %tr
        %td
          = form.label :gender
      %tr
        %td
          = form.label :male
        %td
          = form.radio_button 'gender', 'M'
      %tr
        %td
          = form.label :female
        %td
          = form.radio_button 'gender', 'F'
      %tr
        %td
          = form.label :other
        %td
          = form.radio_button 'gender', 'O'
      %tr
        %td
          = form.label :password
        %td
          = form.text_field :password
      %tr
        %td
          = form.label :password_confirmation  
        %td
          = form.text_field :password_confirmation
      %tr
        %td
          = form.label :dob
        %td
          = form.date_field 'dob'
      %tr
        %td
        %td
          = form.submit
  = link_to 'Back', users_path

app/views/users/show.html.haml
%center
  %h1 User Profile
  %table{:cellpadding => "10"}
    %tr
      %th Name
      %th Gender
      %th EMail
      %th DOB
      %tr
        %td= @user.name+" "+@user.last_name
        %td= @user.gender
        %td= @user.email
        %td= @user.dob
      %tr
        %td= link_to 'Address', user_address_path(@user)